production: &production
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
local: &local
  :url: redis://localhost:6379
  :host: localhost
  # :url: redis://192.168.3.6:6379
  # :host: 192.168.3.6
  :port: 6379
  :timeout: 1
  :inline: true
development: *local
test: *local