# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f53990b16774a618caadf97c60fbfd3c73708b6cc285255f7d986cc58b3f68ed5e13bdb8b34b7b02349fb63db575d6e34e47ec8d8403e9ae839333328e7f486f

test:
  secret_key_base: f0f6be8671863d3376fe830256469ee5e08712b01b297c88eb824cc2c33069bd8a36c5f5c31754ac5bbd7263d6135612dc8054d19bb7e639a451d02788c7a3be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
